apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kaniko
generatorOptions:
  disableNameSuffixHash: true
bases:
  - ../../base
namePrefix: flask-portfolio-
nameSuffix: "-001"
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Pod
  metadata:
    name: kaniko
    namespace: kaniko
  spec:
    containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
      - "--context=git://github.com/AbeYuki/flask-portfolio/"
      - "--destination=registry.gitlab.com/aimhighergg/docker-registry/flask-portfolio:1.0"