apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kaniko
generatorOptions:
  disableNameSuffixHash: true
bases:
  - ../../base
namePrefix: flask-portfolio-
nameSuffix: "-001"
patchesStrategicMerge:
- |-
  apiVersion: batch/v1
  kind: Job
  metadata:
    name: kaniko
    namespace: kaniko
  spec:
    template:
      spec:
        containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--git=branch=build"
            - "--context=git://github.com/AbeYuki/flask-portfolio/"
            - "--destination=registry.gitlab.com/aimhighergg/docker-registry/flask-portfolio:1.0"
            - " --target=linux/arm64,linux/amd64"