apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kaniko
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: git-credential
  files:
  - git-username=git-username.txt
  - git-password=git-password.txt
- name: docker-registry
  files:
   - '.dockerconfigjson=docker-registry.json'
  type: kubernetes.io/dockerconfigjson
